[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['npm install --legacy-peer-deps', 'npx prisma generate']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'node dist/main.js'
